/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:712298fb-6896-405b-aee9-6ea60b50a284",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fxAprBldh",
    "aws_user_pools_web_client_id": "vm307q4s1saart56l7rg2bcpl",
    "oauth": {}
};


export default awsmobile;
